### ISSUE TITLE
关于 clash 规则使用 PROCESS-NAME

### ISSUE THREAD

**Issue by NormanBB** [HoldOnBro/WinRoute2ClashRules#1]
在[Clash for Windows 文档](https://docs.cfw.lbyczf.com/contents/ui/profiles/rules.html)中提到，可以在rules中配置进程名并开启TUN模式来使用代理，个人觉得规则可以利用这点，因为IP规则存在更新不及时的缺点。

**Comment by HoldOnBro** [comment]
使用电脑端 Clash 的话确实是用 process-name 比较方便，不过我的使用场景是在软路由上跑openclash，所以还是只能用cidr ip的方式。个人觉得process-name自行手动添加规则就行了，似乎没有专门写个脚本实现的必要？可以说说你的使用场景吗？
